// <auto-generated />
using System;
using HelloWorld;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HelloWorld.Migrations
{
    [DbContext(typeof(OurDbContext))]
    [Migration("20250525214424_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HelloWorld.Lesson", b =>
                {
                    b.Property<int>("Series_id")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<TimeSpan>("Custom_duration")
                        .HasColumnType("interval");

                    b.Property<DateTime>("Custom_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Has_occured")
                        .HasColumnType("boolean");

                    b.Property<bool>("Is_confirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Tutor_info")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Series_id", "Ordinal");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("HelloWorld.Serie", b =>
                {
                    b.Property<int>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeriesId"));

                    b.Property<DateTime>("BeginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EndOrdinal")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("LessonDuration")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("Offset")
                        .HasColumnType("interval");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("Student_id")
                        .HasColumnType("integer");

                    b.HasKey("SeriesId");

                    b.HasIndex("StudentId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("HelloWorld.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("HelloWorld.Lesson", b =>
                {
                    b.HasOne("HelloWorld.Serie", "Serie")
                        .WithMany("Lessons")
                        .HasForeignKey("Series_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("HelloWorld.Serie", b =>
                {
                    b.HasOne("HelloWorld.Student", "Student")
                        .WithMany("Series")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("HelloWorld.Serie", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("HelloWorld.Student", b =>
                {
                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
