AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 10
    MemorySize: 512

Resources:
  GetLessonsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Endpoints/
      Handler: Endpoints::Endpoints.GetLessonsFunction::GetLessonsHandler
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512
      Events:
        GetLessons:
          Type: Api
          Properties:
            Path: /api/lesson
            Method: get
  PlanLessonsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Endpoints/
      Handler: Endpoints::Endpoints.PlanLessonsFunction::PlanLessons
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512
      Events:
        GetLessons:
          Type: Api
          Properties:
            Path: /api/plan-lessons
            Method: post
  ConfirmLessonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Endpoints/
      Handler: Endpoints::Endpoints.ConfirmLessonFunction::ConfirmLesson
      Runtime: dotnet8
      Architectures:
        - x86_64
      MemorySize: 512
      Events:
        GetLessons:
          Type: Api
          Properties:
            Path: /api/lesson/{lessonUuid}/confirm
            Method: put
