version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::682761213074:user/aws-sam-cli-managed-ohio-pipeline-reso-PipelineUser-UxVfzXDclTuA"
permissions_provider = "AWS IAM"

[ohio.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::682761213074:role/aws-sam-cli-managed-ohio-pipe-PipelineExecutionRole-1Sb9UXcVWAdX"
cloudformation_execution_role = "arn:aws:iam::682761213074:role/aws-sam-cli-managed-ohio--CloudFormationExecutionRo-uOwTZkJaMB1e"
artifacts_bucket = "aws-sam-cli-managed-ohio-pipeline--artifactsbucket-q4dmvpn1hhlc"
image_repository = ""
region = "eu-central-1"

[rizz.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::682761213074:role/aws-sam-cli-managed-rizz-pipe-PipelineExecutionRole-Ywz4ndVfz9mQ"
cloudformation_execution_role = "arn:aws:iam::682761213074:role/aws-sam-cli-managed-rizz--CloudFormationExecutionRo-jZs7Hni7vkVi"
artifacts_bucket = "aws-sam-cli-managed-rizz-pipeline--artifactsbucket-ummrrkvpzjsc"
image_repository = ""
region = "eu-central-1"
